-- 옵션정보
CREATE TABLE OPTION_INFO(
	OPID VARCHAR2(10) PRIMARY KEY,
	OPNAME VARCHAR2(100)
);

-- 차량별옵션
CREATE TABLE CAR_OPTIONS(
	CAR_NUM VARCHAR2(10),
	OPID VARCHAR2(10),
	FOREIGN KEY (CAR_NUM) REFERENCES OKAY_CAR_REGISTER (CAR_NUM)
	ON DELETE CASCADE,
	FOREIGN KEY (OPID) REFERENCES OPTION_INFO (OPID)
	ON DELETE CASCADE
);

-- 차량별 옵션 join 구문
SELECT oi.*, ok.* 
FROM CAR_OPTIONS co, OPTION_INFO oi, OKAY_CAR_REGISTER ok
WHERE co.car_num=ok.car_num AND co.opid=oi.opid ORDER BY ok.CAR_NUM;

--
INSERT ALL
INTO OPTION_INFO VALUES ('ext-1','LED 헤드 라이트')
INTO OPTION_INFO VALUES ('ext-2','HID 헤드 라이트')
INTO OPTION_INFO VALUES ('ext-3','어댑티브 헤드램프')
INTO OPTION_INFO VALUES ('ext-4','전동접이식 사이드미러')
INTO OPTION_INFO VALUES ('ext-5','선루프')
INTO OPTION_INFO VALUES ('ext-6','루프랙')
INTO OPTION_INFO VALUES ('ext-7','알루미늄 휠')
INTO OPTION_INFO VALUES ('int-1','스티어링 휠 리모컨')
INTO OPTION_INFO VALUES ('int-2','룸미러')
INTO OPTION_INFO VALUES ('int-3','하이패스')
INTO OPTION_INFO VALUES ('int-4','가죽시트')
INTO OPTION_INFO VALUES ('int-5','전동시트')
INTO OPTION_INFO VALUES ('int-6','열선시트')
INTO OPTION_INFO VALUES ('int-7','메모리시트')
INTO OPTION_INFO VALUES ('int-8','통풍시트')
INTO OPTION_INFO VALUES ('int-9','안마시트')
INTO OPTION_INFO VALUES ('saf-1','에어백')
INTO OPTION_INFO VALUES ('saf-2','감지센서')
INTO OPTION_INFO VALUES ('saf-3','후측방 경보시스템')
INTO OPTION_INFO VALUES ('saf-4','전방 카메라')
INTO OPTION_INFO VALUES ('saf-5','후방 카메라')
INTO OPTION_INFO VALUES ('saf-6','360도 어라운드 뷰')
INTO OPTION_INFO VALUES ('saf-7','ABS')
INTO OPTION_INFO VALUES ('saf-8','차체자세 제어장치')
INTO OPTION_INFO VALUES ('saf-9','ECS')
INTO OPTION_INFO VALUES ('saf-10','TPMS')
INTO OPTION_INFO VALUES ('saf-11','LDWS')
INTO OPTION_INFO VALUES ('saf-12','자동긴급제동')
INTO OPTION_INFO VALUES ('saf-13','경사로 밀림방지 장치')
INTO OPTION_INFO VALUES ('con-1','스티어링 휠 열선')
INTO OPTION_INFO VALUES ('con-2','텔레매틱스')
INTO OPTION_INFO VALUES ('con-3','전자식파킹 브레이크')
INTO OPTION_INFO VALUES ('con-4','어토에어컨')
INTO OPTION_INFO VALUES ('con-5','리모컨키')
INTO OPTION_INFO VALUES ('con-6','스마트키')
INTO OPTION_INFO VALUES ('con-7','파워 트렁크')
INTO OPTION_INFO VALUES ('con-8','크루즈 컨트롤')
INTO OPTION_INFO VALUES ('con-9','스마트 크루즈 컨트롤')
INTO OPTION_INFO VALUES ('con-10','CD플레이어')
INTO OPTION_INFO VALUES ('con-11','내비게이션')
INTO OPTION_INFO VALUES ('con-12','고스트 도어클로징')
INTO OPTION_INFO VALUES ('con-13','뒷자석 모니터')
INTO OPTION_INFO VALUES ('con-14','오토슬라이딩 도어')
INTO OPTION_INFO VALUES ('con-15','USB 단자')
INTO OPTION_INFO VALUES ('con-16','블루투스')
INTO OPTION_INFO VALUES ('con-17','핸들 열선')
INTO OPTION_INFO VALUES ('con-18','주차조향 보조시스템')
INTO OPTION_INFO VALUES ('con-19','무선충전')
INTO OPTION_INFO VALUES ('con-20','오토 라이트')
INTO OPTION_INFO VALUES ('con-21','스탑앤고')
INTO OPTION_INFO VALUES ('con-22','HUD')
SELECT * FROM DUAL;


SELECT * FROM OPTION_INFO WHERE OPID LIKE '%con%'ORDER BY opid;
SELECT * FROM OPTION_INFO;

/*
SELECT * FROM OPTION_INFO WHERE OPID LIKE '%%'
 */








